application: ###APPID###
version: 1
# To reduce cost lower to F1. Some features might not work.
instance_class: F4

runtime: python27
threadsafe: yes
api_version: 1

inbound_services:
- warmup

automatic_scaling:
   max_concurrent_requests: 3
   min_pending_latency: 100ms
   max_pending_latency: 450ms
   min_idle_instances: 0
   max_idle_instances: 1

builtins:
- remote_api: on
- deferred: on

libraries:
- name: django
  version: 1.5
- name: webapp2
  version: latest
- name: pycrypto
  version: latest

env_variables:
  DJANGO_SETTINGS_MODULE: 'simian.settings'


handlers:

### Warmup URL

- url: /_ah/warmup
  script: simian.mac.urls.app
  login: admin
  secure: always

### URLs commonly requested by Munki clients

- url: /icons/.*
  script: simian.mac.urls.app
  secure: always

- url: /pkgs/.*
  script: simian.mac.urls.app
  secure: always

- url: /pkgsinfo/.*
  script: simian.mac.urls.app
  secure: always

- url: /catalogs/.*
  script: simian.mac.urls.app
  secure: always

- url: /manifests/.*
  script: simian.mac.urls.app
  secure: always

- url: /reports
  script: simian.mac.urls.app
  secure: always

### Uncomment the following lines to enable client customization.
### -=WARNING=-
### The .zip files stored here are publicly accessible, widely known resources.
### Only enable client_resources if you refrain from including confidential
### details, and are prepared to mitigate abuse.
### For more, see https://github.com/munki/munki/wiki/Client-Customization
# - url: /client_resources
#   static_dir: client_resources
#   secure: always

### Apple SUS integration, client repair, Munki log uploads, etc.

- url: /applesus/.*
  script: simian.mac.urls.app
  secure: always

- url: /repair
  script: simian.mac.urls.app
  secure: always

- url: /uploadfile/.*
  script: simian.mac.urls.app
  secure: always

- url: /auth
  script: simian.mac.urls.app
  secure: always

- url: /api/.*
  script: simian.mac.api.urls.app
  secure: always

### Cron Job Handler

- url: /cron/.*
  script: simian.mac.cron.main.app
  login: admin
  secure: always

### Static content for admin UI

- url: /admin/static
  static_dir: simian/mac/admin/static
  secure: always
  login: required

- url: .*/admin/css
  static_dir: simian/mac/admin/css
  secure: always
  login: required

- url: .*/admin/js
  static_dir: simian/mac/admin/js
  secure: always
  login: required

### Admin UI

- url: /admin($|/.*)
  script: simian.mac.admin.main.app
  secure: always
  login: required


### Catchall handler

- url: /.*
  script: simian.mac.urls.app
  secure: always
  login: required
